version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:3
    #hostname: "spark_master"
    container_name: "spark_master"
    environment:
      SPARK_MODE: "master"
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - plc_pipeline_network
    volumes:
      - /home/herberto/Schreibtisch/BA/plc-pipeline/src/plc4x_connector/src/resources/json/plcdata.json:/jsonSchema/plcdata.json


  spark-worker:
    image: docker.io/bitnami/spark:3
    #hostname: "localhost"
    container_name: "worker1"
    environment:
      SPARK_MODE: "worker"
      SPARK_MASTER_URL: "spark://spark-master:7077"
      SPARK_WORKER_MEMORY: "4G"
      SPARK_WORKER_CORES: "2"
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
    ports:
      - "8081:8081"
    depends_on:
      - "spark-master"
    networks:
      - plc_pipeline_network
    volumes:
      - /home/herberto/Schreibtisch/BA/plc-pipeline/src/plc4x_connector/src/resources/json/plcdata.json:/jsonSchema/plcdata.json

networks:
  plc_pipeline_network:
    name: plc_pipeline_network