# Enter your preferred Datasource (Optional)
# Example: Adding InfluxDB

#apiVersion: 1
#
#datasources:
#  - name: myinfluxdb
#    type: influxdb
#    access: proxy
#    orgId: 1
#    url: http://influxdb:8086
#    isDefault: true