version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper1
    hostname: zookeeper1
    restart: unless-stopped
    ports:
      - '2181:2181'
    networks:
      - plc_pipeline_network
    environment:
      - ALLOW_ANONYMOUS_LOGIN: yes
  
  kafdrop:
    image: 'obsidiandynamics/kafdrop'
    container_name: kafdrop
    hostname: kafdrop
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - plc_pipeline_network
    environment:
        KAFKA_BROKERCONNECT: "kafka1:9092"
        JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka1
    hostname: kafka1
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID: 1
      # Listener is on the same Host-Machine -> ToDo: Change if different Machines
      - KAFKA_CFG_LISTENERS: INTERNAL://:9092
      #- KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper
    networks:
      - plc_pipeline_network
# ADD Kafka-Connect here of PLC4X with Confluent Container

networks:
  plc_pipeline_network:
    name: plc_pipeline_network